# Generated by Django 4.0.6 on 2022-12-13 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_sender_chatmodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(default=None, max_length=120),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='reciever',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
