# Generated by Django 4.0.6 on 2022-12-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_chatmodel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
    ]
