# Generated by Django 4.0.6 on 2022-12-13 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_chatmodel_sender_chatmodel_username_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.CharField(blank=True, default=None, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='chatmodel',
            name='reciever',
            field=models.CharField(blank=True, max_length=123, null=True),
        ),
    ]
