# Generated by Django 4.0.6 on 2022-12-13 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0009_remove_chatmodel_username_chatmodel_sender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notified_user', models.CharField(blank=True, max_length=120, null=True)),
                ('notification_text', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('notified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
