# Generated by Django 4.0.6 on 2022-12-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='notify_count',
            field=models.IntegerField(default=0),
        ),
    ]
