# Generated by Django 4.0.6 on 2022-12-13 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_notifications_notify_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='notified_user',
            new_name='notify_receiver',
        ),
        migrations.RenameField(
            model_name='notifications',
            old_name='notified_by',
            new_name='notify_sender',
        ),
    ]
