# Generated by Django 4.0.6 on 2022-12-15 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0014_chatmessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messsage_receiver', models.CharField(blank=True, max_length=120, null=True)),
                ('notification_text', models.TextField()),
                ('thread_name', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('notify_count', models.IntegerField(default=0)),
                ('message_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
