# Generated by Django 4.0.6 on 2022-12-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_chatnotifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatnotifications',
            old_name='messsage_receiver',
            new_name='message_receiver',
        ),
    ]
