# Generated by Django 4.0.6 on 2022-11-18 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_follower_follower_alter_follower_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follower',
            name='user',
            field=models.CharField(max_length=120),
        ),
    ]
