# Generated by Django 4.0.6 on 2022-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='liked_user',
            field=models.CharField(default='', max_length=120),
        ),
    ]
