# Generated by Django 4.0.6 on 2022-11-24 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_likepost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked_user',
        ),
    ]
