# Generated by Django 4.0.6 on 2022-11-26 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_data',
            new_name='comment_date',
        ),
    ]
