# Generated by Django 4.0.6 on 2022-12-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_rename_username_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accounts',
            old_name='is_logged',
            new_name='is_deactivated',
        ),
    ]
