# Generated by Django 4.0.6 on 2022-12-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_rename_is_logged_accounts_is_deactivated'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
