# Generated by Django 4.0.6 on 2023-01-13 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_accounts_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
